import sqlite3

conn = sqlite3.connect('school.db')
cur = conn.cursor()

# Remove temporary test classes generated by test runners
cur.execute("""
    DELETE FROM class_sections 
    WHERE name LIKE 'Test%' 
       OR name LIKE 'Priv%' 
       OR name LIKE '%Test%'
       OR name LIKE '%STEM%'
""")
conn.commit()

remaining = cur.execute('SELECT id, name FROM class_sections').fetchall()
print(f"Remaining classes ({len(remaining)}):")
for r in remaining:
    print(f"  - [{r[0]}] {r[1]}")

conn.close()
